name: Testing

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Installing dependencies
        run: npm install
        
      - name: Testing
        run: npm test
        env: 
          DB: ${{secrets.DB}}
          JWT_SALT: ${{secrets.JWT_SALT}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          SET_PASSWORD_JWT: ${{secrets.SET_PASSWORD_JWT}}
          JWT_EXPIRES_IN: ${{secrets.JWT_EXPIRES_IN}}
          NODE_ENV: ${{secrets.NODE_ENV}}
          SENDGRID_APIKEY: ${{secrets.SENDGRID_APIKEY}}
          SENDGRID_CREATE_PASSWORD_TEMPLATE_ID: ${{secrets.SENDGRID_CREATE_PASSWORD_TEMPLATE_ID}}
          SENDGRID_FORGET_PASSWORD_TEMPLATE_ID: ${{secrets.SENDGRID_FORGET_PASSWORD_TEMPLATE_ID}}
          SENDGRID_NO_REPLY_EMAIL: ${{secrets.SENDGRID_NO_REPLY_EMAIL}}
          SENDGRID_RETURN_EMAIL: ${{secrets.SENDGRID_RETURN_EMAIL}}
          SERVER_HOST: ${{secrets.SERVER_HOST}}
          FRONTEND_HOST: ${{secrets.FRONTEND_HOST}}
          STRIPE_SECRET_KEY: ${{secrets.STRIPE_SECRET_KEY}}
          GOOGLE_PLACES_BASE_URL: ${{secrets.GOOGLE_PLACES_BASE_URL}}
          GOOGLE_PLACES_API_KEY: ${{secrets.GOOGLE_PLACES_API_KEY}}
          AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}
          AZURE_STORAGE_BASE_URL: ${{secrets.AZURE_STORAGE_BASE_URL}}
          AZURE_STORAGE_ACCOUNT: ${{secrets.AZURE_STORAGE_ACCOUNT}}
          AZURE_STORAGE_ACCESS_KEY: ${{secrets.AZURE_STORAGE_ACCESS_KEY}}
          ADMIN_EMAIL: ${{secrets.ADMIN_EMAIL}}
          ADMIN_PASSWORD: ${{secrets.ADMIN_PASSWORD}}
          BIOMETRIC_SIGNATURE_KEY: ${{secrets.BIOMETRIC_SIGNATURE_KEY}}
          BIOMETRIC_JWT_SECRET: ${{secrets.BIOMETRIC_JWT_SECRET}}
          TRIP_VERIFICATION_SECRET: ${{secrets.TRIP_VERIFICATION_SECRET}}
